### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by alexis-via** [m3nu/invoice2data#15]
Here is the error:

```
odoo@ns348518:~/erp$ sudo pip install invoice2data
[sudo] password for odoo: 
Downloading/unpacking invoice2data
  Downloading invoice2data-0.2.0.tar.gz (358kB): 358kB downloaded
  Running setup.py (path:/tmp/pip_build_root/invoice2data/setup.py) egg_info for package invoice2data
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/invoice2data/setup.py", line 3, in <module>
        version = open('VERSION').read().strip()
    IOError: [Errno 2] No such file or directory: 'VERSION'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/invoice2data/setup.py", line 3, in <module>

    version = open('VERSION').read().strip()

IOError: [Errno 2] No such file or directory: 'VERSION'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/invoice2data
Storing debug log for failure in /home/odoo/.pip/pip.log
```

**Comment by m3nu** [comment]
That's a problem. Checking it out now.

**Comment by m3nu** [comment]
Works now. Sorry for the trouble.
