### ISSUE TITLE
Improve error message when pdftotext is missing

### ISSUE THREAD

**Issue by alexis-via** [m3nu/invoice2data#20]
Currently, when pdftotext is not installed, we get this error:

```
% python -m invoice2data.main ~/new_boite/pdf-invoices/test/sfr-facture.pdf
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 96, in <module>
    main()
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 84, in main
    res = extract_data(f.name, templates=templates)
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 23, in extract_data
    extracted_str = pdftotext.to_text(invoicefile).decode('utf-8')
  File "invoice2data/pdftotext.py", line 13, in to_text
    stdout=subprocess.PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

But this error message doesn't give a clue about the cause of the problem. We should try to improve that if possible I think.

**Comment by lepickle** [comment]
I was thinking if we could use imp to check if the package is installed in the system?

**Comment by m3nu** [comment]
[`img`](https://docs.python.org/2/library/imp.html) seems to deal with Python packages, rather than binaries. So using [`shutil.which`](https://docs.python.org/dev/library/shutil.html#shutil.which) seems more appropriate. I'll add it when I do my next batch of accounting in a few weeks.

**Comment by m3nu** [comment]
Thought I'd fix this in the old year.
