### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by lesander** [m3nu/invoice2data#27]
```
macbookpro:~ sander$ pip install invoice2data
Collecting invoice2data
  Using cached invoice2data-0.2.47.tar.gz
Collecting pytesseract (from invoice2data)
  Using cached pytesseract-0.1.6.tar.gz
Collecting pillow (from invoice2data)
  Using cached Pillow-4.0.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyyaml (from invoice2data)
  Using cached PyYAML-3.12.tar.gz
Collecting dateparser (from invoice2data)
  Using cached dateparser-0.6.0-py2.py3-none-any.whl
Collecting unidecode (from invoice2data)
  Using cached Unidecode-0.04.20-py2.py3-none-any.whl
Collecting pdfminer.six (from invoice2data)
  Using cached pdfminer.six-20160614.zip
Collecting olefile (from pillow->invoice2data)
  Using cached olefile-0.44.zip
Collecting tzlocal (from dateparser->invoice2data)
  Using cached tzlocal-1.3.tar.gz
Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from dateparser->invoice2data)
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from dateparser->invoice2data)
Collecting ruamel.yaml (from dateparser->invoice2data)
  Using cached ruamel.yaml-0.13.14.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/tmp_ruamel_J1xp6L/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/tmp_ruamel_J1xp6L/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/tmp_ruamel_J1xp6L/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    /var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/tmp_ruamel_J1xp6L/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/tmp_ruamel_J1xp6L/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/tmp_ruamel_J1xp6L/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/pip-build-VrgoKR/ruamel.yaml/setup.py", line 854, in <module>
        main()
      File "/private/var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/pip-build-VrgoKR/ruamel.yaml/setup.py", line 843, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kl/c7vdfbm92sz3j_frpf8m5tfm0000gn/T/pip-build-VrgoKR/ruamel.yaml/
```

**Comment by m3nu** [comment]
Thanks for writing in. This error is probably related to you trying to install directly in macOS' system python or the external package `ruamel.yaml` you're installing rather than this project's code.
